name = "UKSF Taskforce Alpha - Zeus Modpack";
author = "UKSF Taskforce Alpha Team";
logo = "z\uksfta\zeus\data\icon_128_ca.paa";
logoOver = "z\uksfta\zeus\data\icon_128_highlight_ca.paa";
logoSmall = "z\uksfta\zeus\data\icon_64_ca.paa";
overview = "UKSF Taskforce Alpha - Zeus Modpack. Specialized tools and assets for unit mission makers.";
picture = "z\uksfta\zeus\data\title_co.paa";
tooltip = "UKSFTA Zeus";
tooltipOwned = "UKSF Taskforce Alpha";
